spring:
  mail:
    host: smtp.gmail.com
    password: //generate the app pasword
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: msainithin_ece190491@mgit.ac.in
